source 'https://rubygems.org'

ruby '2.3.5'

gem 'rake'
gem 'rubocop'
gem 'sinatra'
gem 'dm-postgres-adapter'
gem 'data_mapper'

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop-rspec'
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
end
